[google]
type = "service_account"
project_id = "comercial-447112"
private_key_id = "df51f78f29dc7249d7a0e25db7085292c086b49f"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCf7Sy0Q9Dp9vkb
mxDFpzFZ7xecjUAKCsnqS/thxQ5GnlvA3ecI6p3ActBWNR9LRcof9/jza1FclWtS
BZi9cWuPTLTG2i0ZzHhz2e/my4p4It3oYhw6OYoA4O246cW7ZpH4KBs3pploUPkO
DdZl70C/rhiqlZPrn+8+mi/zfKpyF3uDdoFtvSTVzzJKWvQXubL2Ffcm4xiBO3Kn
IFHY7CD+dIXd/gdTuwcgL3v00aVGWHbwj6qMQklYkdK1IrIt+HHKM/f8N8qyNYMN
Gc1bPnXgoEviMxWYWENktIm6NqJnBesdMTy3MmSrMnH1SENrJAbjVFdf1BKFNdhC
J++T3LezAgMBAAECggEAJCnKD5M8NQOzbdIhN0ioyLjfgneQURUCdpgq5n9cTIy3
m8Ox4BrJhECSKsRFaMyFubfllAmi8sgY5gm88a2pkFRclpC0XR6W6D+SV4KUM7lS
q58v2dyz/6HdL5CxNUCq5k4PZYSnMOcKgmqPnio9Xnq8Oiqrsb7PJz1PdYQtuLGK
IRkEv7nQRoQLRofwAwC3C8/TS4544ZCH3PQU4qEfxBIRHeblKQ0f8aH2pRozeoYw
zfA7FD+X9W2yfLPJX5AZw3A5dGkXleaQrY9GxgGTW0X7ti5ZHgrV/lZxuJh9emcV
YFr1VUTe+iF6NTOcIryOCDae+P6rDyfgYc7BNYjhMQKBgQDQNsOWYy9rrROOfsHG
9UdQTF4nLUjk2De6PL3K/Q4/B2KttfnO/IK/s4fwFIrVC8X25inpZjTtbPWoWmLb
WgtqPm8lFBzxloa5rUT7hx62z1Dfvgl/ren38zG8XFpQOGKgYvHMz2CwAFTpMV85
ZYPhuk1egVRbcEIMPxSkcdpdwwKBgQDEoV4Trxnji44ZX4Zw+ziXtDbqpiCOOt+k
zPRPNI3Vk27dUDSa4CZxcLcxPEZarilysZ1Ifrgqhf+dzUz89JELqk94nD4xHQcO
4oo2u6GeYwWFr/16gvc/Id4mIZPV9nxkug1P0qMWDXgeQ8DwakW5wE5s0FcIXsaz
ep8WXxTvUQKBgAQZL9xj82kBLSNe512NMmwoNKo8v/SRNPebfnjiZkdjU9PrgxFJ
8yDm3cQiA2GSK8FiYmzPsDcEMAmyTcPXj+X1eKaYMMGontpEyNjSng4nIoZk7Tbw
K2zQAqicgMKXeYmCqRPI+TQ9rW4xpJgyoVfuHNvBW/G40fP/wd5Cx3OVAoGAaaxj
l+aR3kVBAAfjg9KvrnAO13qiom2nhbUUU4Dl/PM4ML6LFvUCFBNEkLRZByD0a4xi
//QCW/AZ2R/dkVCKpx9HiIVHszNreKdtKk8aY7nJ3PghHPdHk2lLL2j6P5Ixdhy7
TLviI9bnSDSXe11Rzas5OqeZLolo9kofN3GwGZECgYEAmxmgQGjbkDTj8TSwQB1F
+6jKoJR7+PHKfcvITSKLHW3XuNhg9V/swK3g3UwoyQuDPFrm5ayn5sQSyh7DGllB
tsyylifssmjRP6G9TZYGCaA65w/oOIrNzP99ECm6OKfyGxcCelQZAo4a7++vFzvp
fe9eWwux5q5lf6bG7/FBTdM=
-----END PRIVATE KEY-----"""
client_email = "extra-o-comercial@comercial-447112.iam.gserviceaccount.com"
client_id = "112170784520261428010"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/extra-o-comercial%40comercial-447112.iam.gserviceaccount.com"
universe_domain = "googleapis.com"