[google]
type = "service_account"
project_id = "comercial-447112"
private_key_id = "1a8fba9bcd2f5833aaf872abbf87e10232cf67c0"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCe9jiflRnEAUSx
tp2+U6gf27l02/RsYY+YfG4blVRGM3qzk/ZsE0XIvBblBCBTZ/5j1aG0flinAINo
5pjCg+AiUUJrUmOvfAZpoY52jdif7kr4Cq3IPkSfoJz2Bldvwy3g7ZP1w199YSQK
qNh+Q9cTYFOLTit2WpBhkgi6vmIYhrwiCp/erLwFSXlTYM6us+O9PslqsrX+1hrT
ejC8c0NnofWyHbCkF/w0JG6P1S4y6VM3uGkB1/zhmyG0acivdBivGSfSkJy0Jx15
4/FUSy9AGauZkIZljF3w9ZCxJlOAOdKtIvxaYbBdRMDxFwzEzn1otCgrty22LuU8
zFI0AVpnAgMBAAECggEACiqWVBZ1r5eixhIQ12np3oe8V63z9ugfOYUtVMd7Iulx
JBttbvU+/E4s0XhiSazkxyVgxZAv3HzOHev8wkv4dLMC7ww1r4GpUCFZLcBEP3Sl
B/7e2GfeSa5vyDt/MhJzuucjrfWEN036jFGTu8rCiAAcHiFH6rZy3EEG6X9gx+kU
Is1outJEiNtN2XwfpK6zsOLdXyIIBgFnPqKhswbr8wGLOZEEklLbCih3GWTM9xL+
4P4n7W08DkwS+b5Nd44qGeXMsrhrs4sKANlyIiHhtD7rbHeXEEhCg+DMYnzx0Yt6
7tIOWqqBBSTfe77CFlb860rdwbEi5fOon7wEIb5q2QKBgQDd/9oBtCt2zZYT/fT1
LhvD9X5oISPL2ki7cvX1Z8A9NnvOWkF0KfFs4CV7e8RxHh1TCYStEZM3FPVN+N+T
kz7UxQBd/bzSCE3rD0+r9SefdTixibUS1u/+psXi497hEpET8xr+G0wXdxHkU+2h
HlVwDE9JjRn2qvNEmA9qsUudzQKBgQC3TsrBy/gtu1g/5NUwK7yQh6v24/x9fvg7
CJjUwPnjP3W8V0u39HNP4Uk6eWxk2Bzbnsckr/sYk2LFlgJVfWrA4yb7qcjuSBmy
r46aoxe/QQzNPn7AlWIE3MDCKOlq+LCYR0Ry+34VUsCF62Mi/7CwrVWx6df43JWo
OtCg2K+FAwKBgEX66AsPc4AQ0JVewcAkF8aO9Zj3kWQqXDESzSvd18C0ExT6aJWo
vx0WD1q8qjEKUC4j2vn/h0uexLEemcPYb778luAKI2KGEaHegrvvHN1sQ0Hb6gOV
U7QPeGPMdy61/puuT7z4d+URuMckGc1nVYFrr/a8jwmt29+sm3eDihWlAoGAebQe
ejzqMbLJDOLpiGoBcBQj4G/OG6RJOyiiD99wCakAimOLKj9qsAZrkB8+EFZMEqSA
o6MTm2V/lp/aPNhgIGCwaTZ46XuFVFWq4JCYG6sczMhJb6O+yGuor0BqeVNULEZk
89J2C8I9gKyfzYTl0ufClbUkZ15NHryt95zmK/ECgYEAuL9qR+bjI/ycefp4giGR
+o38bdBso21I/yWy1eXxEMFNboI/pvVazJ2/rgkv194LxPOnn8eioVT3EYw38cf5
13fs/C9uRVLmSBpatD0ItstRhblqWegsJ9RY1fmeNfP/Z5/Q/ehvuSPDPb5NAgdL
nbFe0KFKPcrl7jk0A2hdAbg=
-----END PRIVATE KEY-----"""
client_email = "extra-o-comercial@comercial-447112.iam.gserviceaccount.com"
client_id = "112170784520261428010"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/extra-o-comercial%40comercial-447112.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
