[google]
type = "service_account"
project_id = "comercial-447112"
private_key_id = "6d38210fe4b84524cb1a238c5a7d9f248dea9cf3"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDSuoS95eDtjESB
KNL6WFAOCatUeeb0IfKTTNyrAMMXBAvlg5C1X/ylUlffIXBWWsTlcX7usfxMupCv
0uq8w+416vzqfxcfjWZ8eNUTXk8bNlsmzhHoU5NzzniI8iApn/TDriVoIPKgWAWU
B6LBlH1lX4r12bvYHek3gJUOh9SrbX2FjBBH1+4AbwCQ2veQV+bhN/tty4kHfl0e
a5CyZiOigKlwqmqZZrfK7dWslzeBUOJF7lvbsESs4wSB86DgddyiGyruPqVNIZHt
B1jp7P+ialWvQrqWM8L1Iw6o2S1iEpjtVw8ip3qRtoQdl41rZH4h6TUlW+IWWSIO
sZ+ZpNH3AgMBAAECggEAAOONEJpvu2Z6Z/iGHO1OTTV3mvdyS8/5QKYDMrc4t6Yi
2y9SlJFG2KkZcachRP2bd3wpRsVKlDRYGs+FUfWi1e8MZLTCS25RxKexfH9TrkyV
7CYvMDQyc72eO6jm0M/lPOvC9euM2EeOXRySDJIsjgxEwDGt38Yb6k442T6sNhAD
73j9s7GIGIrV/lBHe/MxCTm100HTJ7N35UYaKjQtRQoKTKUyve7I61erKJ+aVmMi
2ixJMowSyxrkSMXRH+CdF0JePOQRGJQ0LeTSKHzWrVvZQdW+Va9G1DNEyialXy+3
Wy1p5K1q4GdicB65HkpkQt98cS8+wjzVAzfqtlUZ4QKBgQD3xJiDvrnXI6WQZeuC
mzn4EUxsfz8tHSbfh+Igz0tP0CVit7V6CEtYUP0lNM8Auqa9b8HeSe/b4WYLKewE
/F7ISCenPL5RkoHHBKSxVKvf1T5OWCv8kGrjnDHjIt053XsLgBn8MIif/rxRxKuk
ApdTZWKwbt/etHJVUQUdoa5siQKBgQDZuuHi63SssJJqHKaYcAyaE4mdu1vCcMfO
pRrMbeKnH6+MP48jeQ9AX+/hQ0fHgFUN7rxIZ6vUog9iwRk4gVKswClgp91KT1j+
HIrp3RDtLA2i1YzOf8mnC0hWsNq1tK5fxY2DRoMXu9vYlhCXkvGKkN+tb0uArNYC
R6i18TqqfwKBgQDA4qAJEFYFEo811uJ9jvKWGIFyha1dJbC5nEOCX162B8jTDUmO
cx6U5pfseywb2TMtju9SaiT8/IBAeKZxSzdOnD2iiDtxraiykv7TvqL/YjdbLnEv
8g4Em/iKZv3qqm28CkIwfmgehmV9Eqq8x/eeyPMHf4lxCvFnUee1pcTwYQKBgQCM
ONZHTTqMCP+ShTcpj2geRpznT4Wt+PJFfIGAzPgeh8KIAVsPDmUrIV4c5jaxHk4o
tereep3oSCK+h/vVLzxucydyz0kuFWIL7ZftO2kuRaPWjc+sIhJdmV+SLT39rgpr
NZCIzf2ZaGwS1bqD06fphJn5WWb3zNfbCgl2e5A7wwKBgE/Eqzmog/2MmIQHx+hm
CqlEM3x5oyimIsRZbEc2nTSrFRQAHlo95Tf8SvrzslSwJhSGlpggMNNOoOiMcKtu
lGXF0iZq0H7xtA54VRuh/X29PQqtPVNdVg28woHuksSBYdcSoM/2L+GYe66DGyBy
XtLSAS2YOaxCn+oaqWSGa2e5
-----END PRIVATE KEY-----"""
client_email = "extra-o-comercial@comercial-447112.iam.gserviceaccount.com"
client_id = "112170784520261428010"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/extra-o-comercial%40comercial-447112.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
